### ISSUE TITLE
Cannot find module "Data.Atomics.Counter.Unboxed"

### ISSUE THREAD

**Issue by peti** [rrnewton/haskell-lockfree#44]
chaselev-deque-0.5.0.3 doesn't seem to compile with GHC 7.8.4 on Linux/x86_64: http://hydra.cryp.to/build/467361/nixlog/1/raw.

**Comment by jberryman** [comment]
Oops, my fault; I should have checked what other packages in this repo were affected by 4a264199. PR is coming

**Comment by peti** [comment]
Can you please release the new version to Hackage?

**Comment by peti** [comment]
Ping?

**Comment by rrnewton** [comment]
Thanks for the ping -- unfortunate lapse due to ICFP deadline ;-) -- this should be fixed by the 0.5.0.5 release that is up now.  Could you confirm that it's all good for you now?

**Comment by rrnewton** [comment]
FYI things look ok on Travis -- https://travis-ci.org/rrnewton/haskell-lockfree/builds/53505277

**Comment by peti** [comment]
The new versions work fine: http://hydra.nixos.org/job/nixpkgs/haskell-updates/haskellngPackages.lockfree-queue.x86_64-linux. Sorry for the late response; this fell through the cracks somehow.
