### PR TITLE
Fix chaselev-dequeue import of Data.Atomics.Counter.Unboxed

### LINKED ISSUE #44: Cannot find module "Data.Atomics.Counter.Unboxed"
chaselev-deque-0.5.0.3 doesn't seem to compile with GHC 7.8.4 on Linux/x86_64: http://hydra.cryp.to/build/467361/nixlog/1/raw.

### PR DESCRIPTION
**Pull request by jberryman**
Fixes #44

### CODE REVIEW

**Comment by rrnewton** [comment]
Thanks!

**Comment by peti** [comment]
A new release to Hackage that contains this fix would be very much appreciated.

**Comment by rrnewton** [comment]
@peter-fogg I added you to the maintainer group.  Could you run tests / check Jenkins and do the upload?
